plugins:
  - jemoji

title: Srameks # your name (or website title) here
logo: "/images/NJ252.JPG?raw=true" # your photo (or logo) here
description:
First description 
<br> Saw a funky email domain and got curious? </br>

theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
